services:
  traffic-keeper:
    image: ghcr.io/pandamelive/pcdn-keeper:latest
    container_name: pcdnkeeper
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
    tmpfs:
      - /tmp
